package com.example.gigpoint

object ProductImageMapper {
    fun getAssetName(productName: String): String {
        val name = productName.lowercase().trim()
        return when {
            "rice" in name -> "Rice"
            "sugar" in name -> "Sugar"
            "wheat flour" in name -> "WheatFlour"
            "atta" in name -> "Atta"
            "maida" in name -> "Maida"
            "salt" in name -> "Salt"
            "toor" in name -> "ToorDal"
            "moong" in name -> "MoongDal"
            "urad" in name -> "UradDal"
            "chana" in name -> "ChanaDal"
            "milk" in name -> "Milk"
            "curd" in name -> "Curd"
            "butter" in name -> "Butter"
            "paneer" in name -> "Paneer"
            "cheese" in name -> "Cheese"
            "bread" in name -> "Bread"
            "egg" in name -> "Eggs"
            "tea" in name -> "Tea"
            "coffee" in name -> "Coffee"
            "biscuit" in name -> "Biscuits"
            "noodle" in name -> "Noodles"
            "pasta" in name -> "Pasta"
            "chips" in name -> "Chips"
            "coke" in name || "cola" in name || "soft drink" in name -> "SoftDrink"
            "juice" in name -> "FruitJuice"
            "water" in name -> "BottledWater"
            "sunflower" in name -> "SunflowerOil"
            "mustard oil" in name -> "MustardOil"
            "oil" in name -> "CookingOil"
            "tomato" in name -> "Tomato"
            "potato" in name -> "Potato"
            "onion" in name -> "Onion"
            "carrot" in name -> "Carrot"
            "cabbage" in name -> "Cabbage"
            "cauliflower" in name -> "Cauliflower"
            "spinach" in name -> "Spinach"
            "brinjal" in name -> "Brinjal"
            "okra" in name -> "Okra"
            "chilli" in name || "chili" in name -> "GreenChili"
            "apple" in name -> "Apple"
            "banana" in name -> "Banana"
            "orange" in name -> "Orange"
            "mango" in name -> "Mango"
            "grape" in name -> "Grapes"
            "soap" in name -> "Soap"
            "shampoo" in name -> "Shampoo"
            "toothpaste" in name -> "Toothpaste"
            "detergent" in name -> "DetergentPowder"
            else -> "Rice"
        }
    }
}
